### ISSUE TITLE
Adapters do not understand Gzipped response

### ISSUE THREAD

**Issue by NikolasMsomething** [Netflix/pollyjs#207] opened 2019-05-07 21:27 UTC
## Description

Just as preface we are using Jest and setupPollyJest for our testing environment. It seems that `@pollyjs/adapter-node-http` is not returning the .json() promise of a response that's gzipped. 

When we do a node-fetch call without polly
```
import fetch from 'node-fetch';
...
const response = await fetch('https://...', { method: 'post', headers: { 'Content-Type': 'application/json', ... }});
```
when we `console.log` a gzipped or non-gzipped response

```
console.log(await response.json());
```
we get the json object back as expected.

When we integrate polly + `@pollyjs/adapter-node-http`, the `console.log` for a gzipped response is `undefined`, but the plain-text (non-gzipped) response will work as expected.

Does anyone know what might be causing the gzipped response from being `undefined`?

### Config

```js
import NodeHttpAdapter from '@pollyjs/adapter-node-http';

export const setupPollyInTestFile = () => {  
  Polly.register(NodeHttpAdapter);

  let context = setupPolly({
    adapters: [ NodeHttpAdapter ],
    adapterOptions: {
      fetch: {
        context: global
      }
    },
    }
  });

  global.pollyContext = context;
}
```

### Dependencies

```json
{
   "@pollyjs/core": "^2.4.0",
   "@pollyjs/persister-fs": "^2.1.0",
   "@pollyjs/adapter-node-http": "^2.4.0",
   "node-fetch": "^2.5.0",
   "setup-polly-jest": "^0.5.2",
}
```

## Environment

Node.js v10.9.0
npm v6.2.0
darwin v18.5.0
yarn v1.13.0

**Comment by offirgolan** [comment] 2019-05-09 01:38
@NikolasMsomething can you create a reproduction for me to debug with? That would really help in figuring out what the underlying issue is.

**Comment by NikolasMsomething** [comment] 2019-05-10 22:08
Thank you so much for the fast response @offirgolan! I will get a reproduction to you in the coming couple of days. Cheers.

**Comment by NikolasMsomething** [comment] 2019-05-13 15:12
Hello @offirgolan ! Here is a [repository you can fork](https://github.com/NikolasMsomething/test-environment-for-netflix) that almost identically mimics what dependencies I have in my development environment. If you run `yarn test:refresh` it will blow up any past recordings and make subsequent calls for the gzipped response. Any code regarding the actual API call lies in **src/ApiUtil.js** while any polly/test related code can be found in **tests/jestSetup.js** or **tests/TestUtil.js**. Thank you very much!

**Comment by offirgolan** [comment] 2019-05-13 16:22
@NikolasMsomething thanks for creating the reproduction. I ran the test suite and the test you've provided passed. 

```bash
 PASS  src/App.test.js
  ✓ fetches gzipped response and makes a proper polly recording (1629ms)

  console.log src/ApiUtil.js:10
    Response {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]:
       { body:
          Gunzip {
            _readableState: [ReadableState],
            readable: true,
            _events: [Object],
            _eventsCount: 7,
            _maxListeners: undefined,
            _writableState: [WritableState],
            writable: false,
            allowHalfOpen: true,
            _transformState: [Object],
            bytesWritten: 0,
            _handle: [Zlib],
            _hadError: false,
            _writeState: [Uint32Array],
            _outBuffer:
             <Buffer 00 00 00 00 00 00 00 00 4f 00 00 00 00 00 00 00 00 c4 81 02 01 00 00 00 8f 00 00 00 a0 20 fb 2e 01 6a 80 02 01 00 00 00 b0 69 84 02 01 00 00 00 08 00 ... >,
            _outOffset: 0,
            _level: -1,
            _strategy: 0,
            _chunkSize: 16384,
            _defaultFlushFlag: 2,
            _finishFlushFlag: 2,
            _nextFlush: -1,
            _info: undefined },
         disturbed: false,
         error: null },
      [Symbol(Response internals)]:
       { url:
          'https://us-central1-polly-issue-demo.cloudfunctions.net/respond',
         status: 200,
         statusText: 'OK',
         headers: Headers { [Symbol(map)]: [Object] },
         counter: 0 } }

  console.log src/ApiUtil.js:11
    Headers {
      [Symbol(map)]:
       [Object: null prototype] {
         'access-control-allow-origin': [ '*' ],
         'content-type': [ 'application/json; charset=utf-8' ],
         etag: [ 'W/"d-wOuS9ky6sDi1SeQD0i4Mbl1QXyY"' ],
         'function-execution-id': [ 'x3asbys3unyt' ],
         vary: [ 'Origin' ],
         'x-powered-by': [ 'Express' ],
         'x-cloud-trace-context': [ '11839f1f06c30f647025968b39a19564;o=1' ],
         'content-encoding': [ 'gzip' ],
         date: [ 'Mon, 13 May 2019 16:15:14 GMT' ],
         server: [ 'Google Frontend' ],
         'cache-control': [ 'private' ],
         'alt-svc': [ 'quic=":443"; ma=2592000; v="46,44,43,39"' ],
         connection: [ 'close' ],
         'transfer-encoding': [ 'chunked' ] } }

  console.log src/ApiUtil.js:60
    DATA IS HERE { test: true }

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.919s
Ran all test suites matching /App.test/i.
✨  Done in 3.56s.

~/src/temp/test-environment-for-netflix master* 4s
❯ node --version
v10.15.3
```

The issue could be with the node version you're on since we only test maintained LTS versions. I'll try running the test on v10.9.0 and see if I can reproduce it there.

**Comment by NikolasMsomething** [comment] 2019-05-13 16:32
Hello again @offirgolan . I made a very slight mistake when reproducing the problem , but i changed something back that now I think may definitely reproduce it for you. I just pushed the changes up now. What is different is I am now capturing the response.json() found in **src/ApiUtil** in a variable and trying to log that instead. Thanks for the help and sorry about that!

**Comment by offirgolan** [comment] 2019-05-30 23:35
@NikolasMsomething any update on this issue and/or the reproduction?

**Comment by offirgolan** [comment] 2019-07-03 16:16
@NikolasMsomething Im gonna go ahead and close this issue for now. Feel free to reopen if you're able to produce a working reproduction.

**Closed by offirgolan** 2019-07-03 16:16 UTC
Labels: :package: adapter-node-http, bug 🐞
