### ISSUE TITLE
UnhandledPromiseRejectionWarning after upgrade

### ISSUE THREAD

**Issue by isi-gach** [Netflix/pollyjs#92] opened 2018-08-13 13:17 UTC
I'm using the following npm packages
```
"@pollyjs/adapter-fetch": "^1.0.0",
"@pollyjs/core": "^1.0.0",
 "@pollyjs/persister-fs": "^1.0.0",
```
If I try to upgrade `@pollyjs/core` to `1.1.0` or higher I get the following warnings running my tests with Jest:
```
(node:16928) UnhandledPromiseRejectionWarning: Error: [Polly] [adapter:fetch] Unhandled request: GET http://localhost/api/gas-types/.
(node:16928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:16928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16928) UnhandledPromiseRejectionWarning: Error: [Polly] [adapter:fetch] Unhandled request: GET http://localhost/api/location/.
(node:16928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .
```
any ideas how to figure it out why?

**Comment by isi-gach** [comment] 2018-08-14 16:25
@jasonmit 
> 1. What were you upgrading from? Knowing this will help me scope down the bug.

I was using version 1.0.0 for `adapter-fetch` `core` and `persister-fs`
> 2. Besides the UnhandledPromiseRejectionWarning warnings, is your test behaving as expected?

Yes, all the tests pass, the only difference is the warning
> 3. Can you share your test code or reduce it down to something you can share?

I have been trying to extract the test in a new repository without success. The warning is triggered by the following line:
```
app.find('Button[content="HOME"]').simulate('click');
```
the button is redirecting to the home page using `react-router`
```
<Button content="HOME" onClick={() => history.push('/')} />
```
The warning disappear if I call `await polly.flush()` just before to `polly.stop()`
So it's not blocking me anymore. Maybe it would be good to describe that workaround in the polly.js documentation?

**Comment by jasonmit** [comment] 2018-08-15 02:50
Thanks for the feedback.

Let me know if you're able to reproduce at any point. In the meantime, I'll continue to think about the issue.

**Comment by isi-gach** [comment] 2018-08-15 11:25
here you go:
```
import React from 'react';
import { mount } from 'enzyme';
import { Polly } from '@pollyjs/core';
import configService from '../../services/configService';
import PortalApp from '../../PortalApp';

describe('No Match page', () => {
    const polly = new Polly('NoMatch', { adapters: ['fetch'], persister: 'fs' });

    polly.configure({ mode: 'replay' });

    polly.server
        .get('/config.portal.json')
        .intercept((__, res) =>
            res.status(200).json({ ENV: 'development', SERVER_URL: 'http://localhost' }),
        );

    afterAll(() => polly.stop());

    it('display NoMatch after calling a bad Url', async () => {
        const config = await configService.getConfig();
        const app = mount(<PortalApp config={config} />);
        await polly.flush();
        app.find('Router[history]')
            .prop('history')
            .push('BadUrl');
        app.update();
        app.find('Button[content="HOME"]').simulate('click');
        expect(window.location.pathname).toBe('/');
        // return polly.flush();
    });
});
```

**Comment by jasonmit** [comment] 2018-08-16 22:50
I'm still unable to reproduce it, but if you remove the `await polly.flush()` and uncomment the `return polly.flush()` does the issue still occur?

**Comment by isi-gach** [comment] 2018-08-17 08:52
I get a slightly different warning:
```
(node:4154) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'apply' of null
(node:4154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 40)
(node:4154) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'apply' of null
(node:4154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)
(node:4154) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'apply' of null
(node:4154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 42)
(node:4154) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'apply' of null
(node:4154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 43)(node:4154) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'apply' of null
(node:4154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 44)
(node:4154) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'apply' of null
(node:4154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 45)
(node:4154) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'apply' of null
(node:4154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
(node:4154) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'apply' of null
(node:4154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (reje
ction id: 47)
(node:4154) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'apply' of null
(node:4154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (reje
ction id: 48)
(node:4154) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'apply' of null
(node:4154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (reje
ction id: 49)
(node:4154) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'apply' of null
(node:4154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (reje
ction id: 50)
```
maybe [this issue](https://github.com/facebook/jest/issues/5311) could be related?

**Comment by jasonmit** [comment] 2018-08-17 20:18
@isi-gach thanks again and sorry for all the back-and-forth.

I'll continue to think about this and try and reproduce on my end.  If any future travelers have a reproduction please add to this issue!

**Comment by ericbiewener** [comment] 2019-03-07 23:06
I find that this issue occurs if my test finishes before the polly request completes (in my use case, I don't care about the results of the request). I'm using `setup-polly-jest` and calling `polly.flush()` in Jest's `afterEach()` setup method seems to do the trick:

```js
const { testPath } = global.jasmine;

Object.defineProperty(window, "fetch", { value: fetch, writable: true });
Polly.register(NodeHttpAdapter);
Polly.register(FSPersister);

const ctx = setupPolly({
  adapters: ["node-http"],
  persister: "fs",
  persisterOptions: {
    fs: {
      recordingsDir: path.resolve(testPath, "..", "./__recordings__"),
    },
  },
  matchRequestsBy: {
    headers: false,
    order: false,
  },
});

beforeEach(() => {
  global.polly = ctx.polly;
});

afterEach(async () => {
  await ctx.polly.flush()
});
```

**Comment by jasonmit** [comment] 2020-02-02 02:59
Closing as the issue is old and awaiting on `polly.flush()` before your tests end should resolve this for most.

**Closed by jasonmit** 2020-02-02 02:59 UTC
Labels: :package: adapter-fetch, :package: core, :package: persister-fs, investigation needed :male_detective:
