### ISSUE TITLE
ReferenceError: self is not defined while importing pollyjs

### ISSUE THREAD

**Issue by harunurhan** [Netflix/pollyjs#41] opened 2018-06-25 12:01 UTC
I get `ReferenceError: self is not defined` where I try: 

```js
const { Polly } = require('@pollyjs/core');
```

My test environment is `node@8.9.1`, running tests suites with jest & puppeteer.

**Comment by webstercharly** [comment] 2018-06-25 12:50
Experienced this as well. Couldn’t solve or get a work around. 

Tried looking at Polly code but couldn’t think of a solution

**Comment by offirgolan** [comment] 2018-06-25 16:16
As of right now, Polly is a client side library (meaning it will only run in the browser) but we are working towards an isomorphic solution! 

Closing this issue since this is a duplicate of #19.

**Closed by offirgolan** 2018-06-25 16:16 UTC
