### ISSUE TITLE
cannot get records

### ISSUE THREAD

**Issue by spursy** [Netflix/pollyjs#85] opened 2018-08-04 09:09 UTC
i use **@pollyjs/node-server** to init a server, the followed is my code:
```
const { Server } = require('@pollyjs/node-server');
const path = require('path');

const server = new Server({
  quiet: true,
  port: 4000,
  apiNamespace: '/pollyjs',
  recordingsDir: path.join(__dirname, '/recordings')
});

// Add custom business logic to the express server
server
  .app
  .get('/custom', (req, res) => { 
        console.log(`Custom request >> > `);
        res.status(200).json("Successfully");
   });

// Start listening and attach extra logic to the http server
server
  .listen()
  .on('error', () => { /* Add http server error logic */ });
```
When I request http://localhost:4000/custom , system cannot records any request history.

I use node v10.7.0

**Comment by jasonmit** [comment] 2018-08-05 01:43
> When I request http://localhost:4000/custom , system cannot records any request history.

You're expecting it to hit your `/custom` middleware - right?

**Comment by spursy** [comment] 2018-08-05 02:01
@jasonmit yes, Could you give me some advise?

**Comment by sradevski** [comment] 2018-08-06 13:57
I faced a similar issue. It seems that **localhost**-based requests are not intercepted by Polly. 
The code is as follows:
```
 const polly = new Polly('Faked HTTP', {
    adapters: ['xhr', 'fetch'],
    recordIfMissing: false,
    mode: 'passthrough',
  });

  const { server } = polly;
  server.get('*').intercept(handler);
//Handler code, not important
```
And the network call is done from my Jest tests from node (making `fetch` global beforehand)
```
expect.assertions(1);
    const response = await fetch(`${rootUri}/users?business=12345`);

    expect(Object.keys(response.data[0])).toEqual(
      Object.keys(expectedResponse),
    );
```
I tried making the same request, once with `http://localhost:4000/` as root uri, and then with `http://google.com`, and one was intercepted while the other one wasn't.

**Comment by jasonmit** [comment] 2018-08-06 16:34
@spursy I'm curious if you're also using Jest?

Can either of you push a reproduction of the issue somewhere?

**Comment by offirgolan** [comment] 2018-08-06 16:41
@sradevski You've put Polly in passthrough mode via `mode: 'passthrough'` which means it wont handle any requests. You've also turned off `recordIfMissing` so new ones wont be recorded if they are missing. 

If you're trying to intercept all requests yourself via the `intercept` handler, `server.get('*')` wont match anything. You will need to be more specific than that.

```
server.get(`${rootUri}/*`).intercept(handler)
```

**Comment by offirgolan** [comment] 2018-08-06 20:40
@sradevski thats very odd that localhost would not be intercepted when you specify a protocol. I'll see if I can reproduce it. 

Out of curiosity, what is your use-case for intercepting all requests? Maybe it will be enough of a reason to have `.any` support it as well.

**Comment by sradevski** [comment] 2018-08-07 08:00
I am creating a library that returns fake data when doing HTTP requests, and I found Polly's mocking adapters to be quite easy to use, as I can support multiple HTTP clients by creating adapters (for now fetch and XHR are sufficient). 

Although it's not very pretty, I just did 
```
server.get('*').intercept(handler);
  server.put('*').intercept(handler);
  server.post('*').intercept(handler);
  server.patch('*').intercept(handler);
  server.delete('*').intercept(handler);
  server.head('*').intercept(handler);
  server.options('*').intercept(handler);
```
wrote some tests, and it seems it works as expected. `.any()` would of course be much cleaner, but HTTP methods won't really change in the near future so it is not a big deal for me.

**Comment by sradevski** [comment] 2018-08-10 16:01
I found out what the problem was with **localhost**. As suspected, the reason was Jest. More specifically, Jest runs in a `jsdom` environment, meaning it will have some presets applied (such as putting XHR as a global). However, you have to specify a test URL in order to be able to make requests to localhost.

Long story short, if you are making calls to port 4000 of localhost, add it to your Jest config like this:
```
"testURL": "http://localhost:4000",
```

After this, you can make requests to "http://localhost:4000/api/whatever" as expected.

**Comment by jasonmit** [comment] 2018-08-10 20:45
@sradevski thanks for circling back.

I mentioned the testURL issue when adding support for Jest just have not had time to document it yet: https://github.com/Netflix/pollyjs/issues/19#issuecomment-401478425

We'll need to update to docs and/or throw a helpful warning when if we detect Jest and testURL being unset.

**Comment by offirgolan** [comment] 2019-02-18 05:34
Since the release of the node-http-adapter with the usage of fs-persister this should no longer be an issue when using Jest. I'm gonna go ahead and close this issue, feel free to reopen if needed.

**Closed by offirgolan** 2019-02-18 05:34 UTC
Labels: :package: node-server, :package: persister-rest, question 🤔
