### ISSUE TITLE
jsdom support?

### ISSUE THREAD

**Issue by isnifer** [Netflix/pollyjs#47] opened 2018-06-29 09:18 UTC
I got next error when tried to use it in browser-like environment:
```
console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Error: Invalid URI "about:/polly/SimilarItems_366191554"
```

**Comment by jasonmit** [comment] 2018-06-29 20:08
@isnifer I was able to reproduce.  Looking into a fix.

**Comment by isnifer** [comment] 2018-06-29 20:10
@jasonmit thank you! If I can help you — just mention me :)

**Comment by jasonmit** [comment] 2018-06-29 21:18
Here is an example of a jest running Polly: https://github.com/jasonmit/jest-with-pollyjs-example

Because Jest isn't running in a real browser, it doesn't know what to set `location.href` to.  This makes relative URLs to be prefixed with `about:blank`.

You can manually set the `location` context.  I set it to the node-server's URI to avoid any CORs issues (I need to poke at this further as to why that is).
http://jestjs.io/docs/en/configuration.html#testurl-string
https://github.com/jasonmit/jest-with-pollyjs-example/blob/master/package.json#L17

I'll need to dig further if fetch with "just work".  Since jsdom doesn't ship with fetch support, I'll need to see how Polly behaves with the popular fetch polyfill libs.

**Comment by jasonmit** [comment] 2018-06-29 21:35
Closing in favor of tracking under #19 since the two are closely coupled.

**Closed by jasonmit** 2018-06-29 21:35 UTC
